/**
 * Should be autogenerated in the feature
 */
import {Observable} from "rxjs";

export interface IEmpty {
}

export interface IArticle {
  id: string;
  title: string;
  articleType: ArticleType;
  bodyText: string;
}

export enum ArticleType {
  TEXTARTICLE,
  PHOTO,
  VIDEO,
}

export interface INinja {
  id: number;
  name: string;
}

export interface ArticleService {
  findOne(data: { id: string }): Observable<any>;
  findAll(empty: IEmpty): Observable<any>;
  add(article: IArticle): Observable<any>;
}

export interface NinjaService {
  findOne(data: { id: number }): Observable<any>;
  findAll(empty: IEmpty): Observable<any>;
  add(ninja: INinja): Observable<any>;
}
